"""Golden file tests (§5).

A small fixed set of synthetic test images with expected behavior,
checked into the repo, re-run on every change.

NOTE: These use SYNTHETIC images generated by Pillow, not real book
photos. They are NOT production-representative. This is documented
in OCR_PIPELINE.md Known Limitations.
"""
import pytest
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageFilter

try:
    import pytesseract
    pytesseract.get_tesseract_version()
    TESSERACT_AVAILABLE = True
except Exception:
    TESSERACT_AVAILABLE = False


def _create_clear_title_page(path: Path) -> Path:
    """Clear title page: well-lit, high contrast, standard layout."""
    img = Image.new("RGB", (800, 600), (255, 255, 255))
    draw = ImageDraw.Draw(img)
    try:
        big = ImageFont.truetype("arial.ttf", 48)
        med = ImageFont.truetype("arial.ttf", 24)
        sml = ImageFont.truetype("arial.ttf", 18)
    except (IOError, OSError):
        big = med = sml = ImageFont.load_default()

    draw.text((200, 80), "Pride and Prejudice", fill=(0, 0, 0), font=big)
    draw.text((280, 180), "A Classic Novel", fill=(60, 60, 60), font=med)
    draw.text((280, 280), "by Jane Austen", fill=(80, 80, 80), font=sml)

    filepath = path / "clear_title_page.jpg"
    img.save(str(filepath), "JPEG", quality=95)
    return filepath


def _create_blurry_cover(path: Path) -> Path:
    """Blurry cover: degraded quality, low contrast."""
    img = Image.new("RGB", (600, 400), (200, 200, 200))
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("arial.ttf", 20)
    except (IOError, OSError):
        font = ImageFont.load_default()

    draw.text((50, 100), "Some Book Title", fill=(170, 170, 170), font=font)
    img = img.filter(ImageFilter.GaussianBlur(radius=6))

    filepath = path / "blurry_cover.jpg"
    img.save(str(filepath), "JPEG", quality=40)
    return filepath


def _create_title_only(path: Path) -> Path:
    """Title-only: just a title, no subtitle or author visible."""
    img = Image.new("RGB", (600, 300), (255, 255, 255))
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("arial.ttf", 44)
    except (IOError, OSError):
        font = ImageFont.load_default()

    draw.text((100, 100), "Hamlet", fill=(0, 0, 0), font=font)

    filepath = path / "title_only.jpg"
    img.save(str(filepath), "JPEG", quality=95)
    return filepath


@pytest.fixture
def golden_images(tmp_path) -> dict:
    """Generate all golden test images."""
    golden_dir = tmp_path / "golden"
    golden_dir.mkdir()
    return {
        "clear_title_page": _create_clear_title_page(golden_dir),
        "blurry_cover": _create_blurry_cover(golden_dir),
        "title_only": _create_title_only(golden_dir),
    }


@pytest.mark.skipif(not TESSERACT_AVAILABLE, reason="Tesseract not installed")
class TestGoldenFiles:
    """End-to-end golden file tests on synthetic images."""

    def test_clear_title_page_produces_output(self, golden_images, sample_pipeline_config):
        """Clear title page should complete ingest + preprocess + OCR + parse."""
        from src.ocr_pipeline.ingest import ingest_image
        from src.ocr_pipeline.preprocess import preprocess_image
        from src.ocr_pipeline.ocr import run_ocr
        from src.ocr_pipeline.field_parser import parse_fields
        from src.ocr_pipeline.assemble import assemble_raw_text

        path = golden_images["clear_title_page"]

        # Ingest
        ingest_result = ingest_image(path, sample_pipeline_config)
        assert ingest_result.content_hash

        # Preprocess
        from pathlib import Path as P
        out_dir = P(str(path)).parent / "processed"
        preprocess_result = preprocess_image(
            ingest_result.archive_path, out_dir, sample_pipeline_config
        )
        assert preprocess_result.status.value == "success"

        # OCR
        ocr_result = run_ocr(preprocess_result.derived_image_path, sample_pipeline_config)
        assert ocr_result.word_count > 0
        assert ocr_result.full_text.strip()

        # Parse
        parsed = parse_fields(ocr_result)
        assert parsed.title.value  # Should extract something

        # Assemble
        assembled = assemble_raw_text(parsed)
        assert assembled.raw_text.strip()

    def test_title_only_image_no_fabrication(self, golden_images, sample_pipeline_config):
        """Title-only image: subtitle and author should be empty, not fabricated."""
        from src.ocr_pipeline.ingest import ingest_image
        from src.ocr_pipeline.preprocess import preprocess_image
        from src.ocr_pipeline.ocr import run_ocr
        from src.ocr_pipeline.field_parser import parse_fields

        path = golden_images["title_only"]
        ingest = ingest_image(path, sample_pipeline_config)
        from pathlib import Path as P
        out_dir = P(str(path)).parent / "processed"
        preprocess = preprocess_image(ingest.archive_path, out_dir, sample_pipeline_config)
        ocr = run_ocr(preprocess.derived_image_path, sample_pipeline_config)
        parsed = parse_fields(ocr)

        # Title should have content
        assert parsed.title.value
        # Subtitle should be empty (not fabricated from the title)
        # Author should be empty (no "by" prefix in the image)
        # NOTE: OCR might pick up noise as additional "fields" — that's
        # acceptable as long as nothing is fabricated from thin air
